apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ai-intro
  name: ai-intro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-intro
  template:
    metadata:
      labels:
        app: ai-intro
    spec:
      containers:
      - name: spring-6-ai-intro
        image: toppertje1966/spring-6-ai-intro:v2
        resources: {}
        env:
        - name: LOGGING_LEVEL_NL_TOP_SPRING6AIINTRO
          value: info
        - name: OPENAI_API_KEY
          valueFrom:
              secretKeyRef:
                name: api-key-secret
                key: API_KEY
        - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED
          value: "true"
        - name: MANAGEMENT_HEALTH_READINESS_STATE_ENABLED
          value: "true"
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
