apiVersion: v1
kind: Service
metadata:
  labels:
    app: ai-intro
  name: ai-intro
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ai-intro
  type: NodePort
